# Generated by Django 5.0.2 on 2024-03-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_watering'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='memory',
            new_name='capacity',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='processor',
            new_name='plant_name',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='category_id',
            new_name='platn_room',
        ),
        migrations.RemoveField(
            model_name='model',
            name='image',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='inventar_number',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='mac_address',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='model_id',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='responsible_id',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='room_number',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='status',
        ),
        migrations.RemoveField(
            model_name='responsible',
            name='description',
        ),
        migrations.AddField(
            model_name='plant',
            name='plant_image',
            field=models.ImageField(null=True, upload_to='static/images/plants'),
        ),
        migrations.AddField(
            model_name='plant',
            name='plant_num',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='plant',
            name='pomp_pin',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='plant',
            name='pomp_status',
            field=models.CharField(default='Не в сети', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='soil_value',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='plant',
            name='soilpin_num',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='plant',
            name='soilpin_status',
            field=models.CharField(default='Не в сети', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='responsible',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images/responsible'),
        ),
        migrations.AddField(
            model_name='responsible',
            name='position',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='static/images/rooms'),
        ),
    ]
