# Generated by Django 5.0.2 on 2024-03-06 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_memory_plant_capacity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Model',
        ),
        migrations.AddField(
            model_name='responsible',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_image',
            field=models.ImageField(null=True, upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='platn_room',
            field=models.ForeignKey(blank=True, default='False', on_delete=django.db.models.deletion.PROTECT, related_name='category', to='home.category'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='pomp_status',
            field=models.CharField(default='False', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='soilpin_status',
            field=models.CharField(default='False', max_length=70, null=True),
        ),
    ]
