# Generated by Django 5.0.2 on 2024-03-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_model_remove_responsible_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsible',
            name='image',
        ),
        migrations.RemoveField(
            model_name='responsible',
            name='position',
        ),
        migrations.AlterField(
            model_name='responsible',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
