# Generated by Django 5.0.2 on 2024-03-12 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_responsible_image_remove_responsible_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='platn_room',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='category', to='home.category'),
        ),
    ]
