# Generated by Django 5.0.2 on 2024-03-12 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_plant_platn_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='platn_room',
            new_name='plant_room',
        ),
    ]
