# Generated by Django 5.0.2 on 2024-03-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_platn_room_plant_plant_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsible',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images'),
        ),
    ]
