# Generated by Django 5.0.2 on 2024-03-13 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_description_responsible_position_logs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Room',
        ),
    ]
