# Generated by Django 5.0.2 on 2024-03-13 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_category_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='pomp_pin',
            new_name='pump_pin',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='pomp_status',
            new_name='pump_status',
        ),
    ]
