# Generated by Django 5.0.2 on 2024-03-18 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0012_rename_pomp_pin_plant_pump_pin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_value', models.CharField(blank=True, max_length=70)),
                ('soilpin_num', models.CharField(blank=True, max_length=70)),
                ('soilpin_status', models.CharField(blank=True, default='False', max_length=70)),
                ('pump_pin', models.CharField(blank=True, max_length=70)),
                ('pump_status', models.CharField(blank=True, default='False', max_length=70)),
                ('plant_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='category', to='home.plant')),
            ],
        ),
    ]
