# Generated by Django 5.0.2 on 2024-03-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_alter_report_plant_name_alter_report_soil_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='pump_pin',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='soilpin_num',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
