# Generated by Django 5.0.2 on 2024-03-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alter_report_pump_pin_alter_report_soilpin_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='pump_status',
            field=models.CharField(blank=True, default='False', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='soilpin_status',
            field=models.CharField(blank=True, default='False', max_length=70, null=True),
        ),
    ]
