# Generated by Django 5.0.2 on 2024-03-18 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_pomp_pin_plant_pump_pin_and_more'),
        ('monitoring', '0004_alter_report_pump_status_alter_report_soilpin_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='plant_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plant', to='home.plant'),
        ),
    ]
