# Generated by Django 5.0.2 on 2024-03-12 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='static/images')),
            ],
        ),
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='static/images')),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Watering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.CharField(max_length=100)),
                ('w_status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(blank=True, max_length=70)),
                ('plant_image', models.ImageField(null=True, upload_to='static/images')),
                ('plant_num', models.CharField(blank=True, max_length=70)),
                ('capacity', models.CharField(blank=True, max_length=70)),
                ('soil_value', models.CharField(blank=True, max_length=70)),
                ('soilpin_num', models.CharField(blank=True, max_length=70)),
                ('soilpin_status', models.CharField(default='False', max_length=70, null=True)),
                ('pomp_pin', models.CharField(blank=True, max_length=70)),
                ('pomp_status', models.CharField(default='False', max_length=70, null=True)),
                ('description', models.TextField(blank=True)),
                ('plant_room', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='category', to='root.category')),
            ],
        ),
    ]
